//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinic.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicVeterinaryEntities : DbContext
    {
        public ClinicVeterinaryEntities()
            : base("name=ClinicVeterinaryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Specialization> Specialization { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Vet> Vet { get; set; }
        public virtual DbSet<Visit> Visit { get; set; }
    }
}
