//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinic.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Staff_ID { get; set; }
        public string Staff_FirstName { get; set; }
        public string Staff_LastName { get; set; }
        public Nullable<int> Role_ID { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
