//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinic.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Visit_ID { get; set; }
        public System.DateTime Visit_Date { get; set; }
        public Nullable<int> Animal_ID { get; set; }
        public Nullable<int> Vet_ID { get; set; }
        public string Diagnosis { get; set; }
        public string Treatment { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Vet Vet { get; set; }
    }
}
